# Generated by Django 2.0.2 on 2018-02-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRCIrun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField()),
                ('pr_date', models.DateTimeField(db_index=True)),
                ('pr_type', models.CharField(max_length=100)),
                ('pr_url', models.CharField(max_length=100)),
                ('run_name', models.CharField(max_length=100)),
                ('run_logs_url', models.CharField(max_length=100)),
                ('run_result', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='prcirun',
            unique_together={('pr_date', 'pr_url')},
        ),
    ]
