# Generated by Django 2.0.2 on 2018-02-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prcirun',
            unique_together={('pr_url', 'run_name')},
        ),
    ]
